// Language translations - Global variable
window.TRANSLATIONS = {
    en: {
        title: 'MSP2 - OBFX®',
        language: 'Language',
        zoom: 'Zoom',
        plan: 'Plan',
        obfx: 'OBFX',
        obfxPro: 'OBFX Pro',
        autograph: 'Autograph',
        changePassword: 'Change Password',
        exit: 'Exit',
        welcomeTitle: 'Welcome to MSP2 Tool',
        welcomeSubtitle: 'Choose your login method',
        websocketLogin: 'WebSocket Login',
        accountLogin: 'Account Login',
        websocketPlaceholder: 'Paste WebSocket message here...',
        usernamePlaceholder: 'Username',
        passwordPlaceholder: 'Password',
        login: 'Login',
        loading: 'Loading...',
        querySent: 'Query sent...',
        approvedLogin: 'Approved Logging in...',
        banned: 'You\'re banned',
        bannedMessage: 'OBFX does not support logging into this account.',
        backToLogin: 'Return to the Home Screen',
        menu: 'Menu',
        changeMood: 'Change Mood',
        gender: 'Gender',
        gifts: 'Gifts',
        dailyTask: 'Daily Task',
        startEnhanced: 'Start',
        fastStart: 'Fast Start',
        applyMood: 'Apply Mood',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm New Password',
        cancel: 'Cancel',
        enterUsername: 'Enter username',
        findStart: 'Find & Start',
        stop: 'Stop',
        test: 'Test',
        totalFame: 'Total Fame:',
        close: 'Close',
        languageSelection: 'Language Selection',
        currentLanguage: 'Current Language:',
        zoomLevel: 'Zoom Level',
        selectRegion: 'Select Region',
        selectRegionDesc: 'Please select your region before logging in:',
        unitedStates: 'United States',
        europe: 'Europe',
        warning: 'Warning!',
        fastWarning1: 'Fast completion may lead to account suspension or ban.',
        startFastMode: 'Start Fast Mode',
        comments: 'Comments',
        noComments: 'No comments yet',
        status: 'Status',
        openAllGifts: 'Open All Gifts',
        sessionExpired: 'Session expired. Please login again.',
        tokenExpiring: 'Session will expire in 15 minutes.',
        loginSuccess: 'Login successful!',
        loginError: 'Login failed. Please check your credentials.',
        invalidCredentials: 'Invalid username or password.',
        connectionError: 'Connection error. Please try again.',
        friendsSettings: 'Friends Settings',
        friends: 'Friends',
        requestSenders: 'Request Senders',
        blocked: 'Blocked',
        deleteAll: 'Delete All',
        loadingFriends: 'Loading friends...',
        loadingRequests: 'Loading requests...',
        loadingBlocked: 'Loading blocked...',
        noFriends: 'No friends found',
        noRequests: 'No friend requests',
        noBlocked: 'No blocked users',
        level: 'Level',
        lastLogin: 'Last Login',
        remove: 'Remove',
        accept: 'Accept',
        reject: 'Reject',
        unblock: 'Unblock',
        dangerousAction: 'Dangerous Action!',
        deleteAllWarning: 'This action will remove ALL users from the selected category. This is risky and cannot be undone!',
        waitCountdown: 'Wait for countdown to finish...',
        yes: 'Yes',
        no: 'No',
        giftOpenSuccess: 'Gift opened successfully!',
        giftOpenError: 'Failed to open gift',
        giftOpening: 'Opening gift...',
        openingGifts: 'Opening gifts...',
        allGiftsOpened: 'All gifts opened successfully!',
        scammerTest: 'Scammer Test',
        securityStatus: 'Security Status',
        securitySafe: 'Safe',
        securitySuspicious: 'Suspicious',
        securityUnsafe: 'Unsafe',
        description: 'Description',
        loadingComments: 'Loading comments...',
        deletingComment: 'Deleting comment...',
        commentDeleted: 'Comment deleted successfully!',
        upgradeToObfxPlus: 'Upgrade to OBFX Plus',
        upgradeToObfxPro: 'Upgrade to OBFX Pro',
        requiresLevel10OrPlus: 'Requires Level 10+ or OBFX Plus',
        requiresObfxPro: 'Requires OBFX Pro subscription',
        planComparison: 'Plan Comparison',
        freePlan: 'Free',
        plusPlan: 'OBFX Plus',
        proPlan: 'OBFX Pro',
        basic: 'Basic',
        standart: 'Standard',
        recommended: 'Recommended',
        dailyTasksLevel10: 'Daily Tasks (Level 10+)',
        limitedMoods: 'Limited Moods (7)',
        noGifts: 'No Gifts Access',
        friendsManagement: 'Friends Management',
        unlimitedDailyTasks: 'Unlimited Daily Tasks',
        allMoods: 'All Moods (37)',
        giftsAccess: 'Full Gifts Access',
        advancedFriends: 'Advanced Friends',
        prioritySupport: 'Priority Support',
        fastFeatures: 'Fast Features',
        multiAccount: 'Multi-Account Management',
        bulkOperations: 'Bulk Operations',
        detectiveService: 'Detective service',
        vipOnly: 'VIP Only',
        passwordChangeSuccess: 'Password changed successfully!',
        downloadAccountFile: 'Would you like to download your account file?',
        noThanks: 'No, thanks',
        whatsThis: 'What\'s this for?',
        yesRecommended: 'Yes (recommended)',
        accountFileInfo: 'Your account file contains your updated credentials. We recommend downloading and storing it securely as a backup. This file can help you recover your account if you forget your login details.',
        accountFileInfoTitle: 'Account File Information',
        passwordChanging: 'Changing password...',
        passwordChangeError: 'Failed to change password',
        passwordMismatch: 'Passwords do not match',
        passwordTooShort: 'Password must be at least 6 characters',
        fillAllFields: 'Please fill all fields',
        downloadStarted: 'Account file download started',
        currentPasswordWrong: 'Current password is incorrect',
        accountManagement: 'Account Management',
        accountInfo: 'Account Info',
        accountMethod: 'Account Method',
        websocketMethod: 'WebSocket Method',
        save: 'Save',
        reset: 'Reset',
        accounts: 'Accounts',
        normalTasks: 'Normal Daily Tasks',
        fastTasks: 'Fast Daily Tasks',
        accountSaved: 'Account saved successfully!',
        accountsReset: 'All accounts reset!',
        processingAccounts: 'Processing accounts...',
        accountsProcessed: 'All accounts processed!',

        // Account Info Section
        startDate: 'Start Date',
        lastLoginDate: 'Last Login',
        location: 'Location',
        houseName: 'House Name',
        lastUpdated: 'Last Updated',
        numberOfArrangements: 'Number of Arrangements',
        profileAnimLastModified: 'Profile Animation Last Modified Date',
        numberOfChanges: 'Number of Changes',
        homePhoto: 'Home Photo',
        loadingHomeImage: 'Loading home image...',
        homeImageNotAvailable: 'Home image not available',
        theHouse: ' The house',
        searchingForUser: 'Searching for user: ',
        accountInfoLoadedSuccess: 'Account info loaded successfully',
        errorLoadingAccountInfo: 'Error loading account info',
        pleaseEnterUsername: 'Please enter a username',
        userNotFound: ' not found',

        // General Notifications
        pleaseEnterWebsocketData: 'Please enter the WebSocket message data',
        invalidDataFormat: 'Invalid data format. Please check your input.',
        regionNotSupported: 'This region is not supported.',
        noAccountsToProcess: 'No accounts to process',
        accountAlreadyExists: 'Account already exists',
        invalidWebsocketFormat: 'Invalid WebSocket data format',
        noSecurityIssues: 'No security issues reported for this user.',
        autoGreetingStarted: 'Auto-greeting started for ',
        autoGreetingStopped: 'Auto-greeting stopped',
        sendingEveryTwoMinutes: ' - sending every 2 minutes',
        couldNotFindUser: 'Could not find user ',
        autoGreetingAlreadyRunning: 'Auto-greeting is already running',
        pleaseLoginFirst: 'Please login first',
        moodChangedSuccessfully: 'Mood changed successfully!',
        failedToChangeMood: 'Failed to change mood',
        errorChangingMood: 'Error changing mood',
        genderChangedTo: 'Gender changed to ',
        failedToChangeGender: 'Failed to change gender',
        errorChangingGender: 'Error changing gender',
        noGiftsAvailable: 'No gifts available',
        pleaseWait: 'Please wait...',
        friendRemovedSuccess: 'Friend removed successfully',
        errorRemovingFriend: 'Error removing friend',
        friendRequestAccepted: 'Friend request accepted',
        errorAcceptingRequest: 'Error accepting request',
        friendRequestRejected: 'Friend request rejected',
        errorRejectingRequest: 'Error rejecting request',
        userUnblockedSuccess: 'User unblocked successfully',
        errorUnblockingUser: 'Error unblocking user',
        noUsersToDelete: 'No users to delete in this category',
        removingUsers: 'Removing {count} users...',
        allUsersRemoved: 'All users removed from category ({success}/{total})',
        errorRemovingAllUsers: 'Error removing all users',
        failedToOpenAnyGifts: 'Failed to open any gifts',
        errorOpeningGifts: 'Error opening gifts',
        startingEnhancedTasks: 'Starting enhanced daily tasks...',
        startingFastTasks: 'Starting FAST daily tasks...',
        processingPetInteractions: 'Processing pet interactions...',
        completingDailyQuests: 'Completing daily quests...',
        processingVipGifts: 'Processing VIP gift quests...',
        processingNormalGifts: 'Processing normal gift quests...',
        claimingVipRewards: 'Claiming VIP pickup rewards...',
        claimingNormalRewards: 'Claiming normal pickup rewards...',
        processingAdditionalQuests: 'Processing additional quests...',
        allEnhancedTasksComplete: 'All enhanced daily tasks completed!',
        allFastTasksComplete: 'All FAST daily tasks completed!',
        enhancedTasksCompletedSuccess: 'All enhanced daily tasks completed successfully!',
        fastTasksCompletedSuccess: 'All FAST daily tasks completed successfully!',
        errorDuringExecution: 'Error during execution',
        errorDuringDailyTasks: 'Error during daily tasks execution',
        errorDuringFastTasks: 'Error during FAST daily tasks execution',
        fastProcessingAllTasks: 'FAST: Processing all tasks in parallel...',
        fastExecutingSimultaneously: 'FAST: Executing all tasks simultaneously...',
        openedGiftsPartial: 'Opened {success}/{total} gifts successfully',
        loggedOutSuccessfully: 'Successfully logged out. Account credentials and zoom setting preserved.',
        languageChangedTo: 'Language changed to ',
        accountDataNotAvailable: 'No account data available for download',
        errorLoadingFriendsData: 'Error loading friends data',
        loadingConversations: 'Loading conversations...',
        noConversations: 'No conversations found',
        failedToLoadConversations: 'Failed to load conversations',
        errorLoadingConversations: 'Error loading conversations',
        loadingMessages: 'Loading messages...',
        noMessages: 'No messages in this conversation',
        failedToLoadMessages: 'Failed to load messages',
        errorLoadingMessages: 'Error loading messages',
        unknownUser: 'Unknown User',
        failedToLoad: 'Failed to Load',
        errorLoading: 'Error Loading',
        backToInbox: 'Back to Inbox',
        inbox: 'Inbox',
        noMessage: 'No message',
        fromUser: 'From: '
    },
    tr: {
        title: 'MSP2 - OBFX®',
        language: 'Dil',
        zoom: 'Yakınlaştır',
        plan: 'Plan',
        obfx: 'OBFX',
        obfxPro: 'OBFX Pro',
        autograph: 'İmza',
        changePassword: 'Şifre Değiştir',
        exit: 'Çıkış',
        welcomeTitle: 'MSP2 Aracına Hoş Geldiniz',
        welcomeSubtitle: 'Giriş yönteminizi seçin',
        websocketLogin: 'WebSocket Girişi',
        accountLogin: 'Hesap Girişi',
        websocketPlaceholder: 'WebSocket mesajını buraya yapıştırın...',
        usernamePlaceholder: 'Kullanıcı Adı',
        passwordPlaceholder: 'Şifre',
        login: 'Giriş Yap',
        loading: 'Yükleniyor...',
        querySent: 'Sorgu gönderildi...',
        approvedLogin: 'Onaylandı, giriş yapılıyor...',
        banned: 'Yasaklandınız!',
        bannedMessage: 'OBFX bu hesaba giriş yapmayı desteklemiyor.',
        backToLogin: 'Ana Ekrana Dön',
        menu: 'Menü',
        changeMood: 'Ruh Hali Değiştir',
        gender: 'Cinsiyet',
        gifts: 'Hediyeler',
        dailyTask: 'Günlük Görev',
        startEnhanced: 'Başlat',
        fastStart: 'Hızlı Başlat',
        applyMood: 'Ruh Halini Uygula',
        currentPassword: 'Mevcut Şifre',
        newPassword: 'Yeni Şifre',
        confirmPassword: 'Yeni Şifreyi Onayla',
        cancel: 'İptal',
        enterUsername: 'Kullanıcı adını girin',
        findStart: 'Bul ve Başlat',
        stop: 'Durdur',
        test: 'Test',
        totalFame: 'Toplam Şöhret:',
        close: 'Kapat',
        languageSelection: 'Dil Seçimi',
        currentLanguage: 'Mevcut Dil:',
        zoomLevel: 'Yakınlaştırma Seviyesi',
        selectRegion: 'Bölge Seç',
        selectRegionDesc: 'Giriş yapmadan önce lütfen bölgenizi seçin:',
        unitedStates: 'Amerika Birleşik Devletleri',
        europe: 'Avrupa',
        warning: 'Uyarı!',
        fastWarning1: 'Hızlı tamamlama hesap askıya alınmasına veya yasaklanmasına neden olabilir.',
        startFastMode: 'Hızlı Modu Başlat',
        comments: 'Yorumlar',
        noComments: 'Henüz yorum yok',
        status: 'Durum',
        openAllGifts: 'Tüm Hediyeleri Aç',
        sessionExpired: 'Oturum süresi doldu. Lütfen tekrar giriş yapın.',
        tokenExpiring: 'Oturum 15 dakika içinde sona erecek.',
        loginSuccess: 'Giriş başarılı!',
        loginError: 'Giriş başarısız. Lütfen bilgilerinizi kontrol edin.',
        invalidCredentials: 'Geçersiz kullanıcı adı veya şifre.',
        connectionError: 'Bağlantı hatası. Lütfen tekrar deneyin.',
        friendsSettings: 'Arkadaş Ayarları',
        friends: 'Arkadaşlar',
        requestSenders: 'İstek Gönderenler',
        blocked: 'Engellenenler',
        deleteAll: 'Tümünü Sil',
        loadingFriends: 'Arkadaşlar yükleniyor...',
        loadingRequests: 'İstekler yükleniyor...',
        loadingBlocked: 'Engellenenler yükleniyor...',
        noFriends: 'Arkadaş bulunamadı',
        noRequests: 'Arkadaşlık isteği yok',
        noBlocked: 'Engellenen kullanıcı yok',
        level: 'Seviye',
        lastLogin: 'Son Giriş',
        remove: 'Kaldır',
        accept: 'Kabul Et',
        reject: 'Reddet',
        unblock: 'Engeli Kaldır',
        dangerousAction: 'Tehlikeli Eylem!',
        deleteAllWarning: 'Bu eylem seçilen kategorideki TÜM kullanıcıları kaldıracak. Bu riskli bir işlemdir ve geri alınamaz!',
        waitCountdown: 'Geri sayımın bitmesini bekleyin...',
        yes: 'Evet',
        no: 'Hayır',
        giftOpenSuccess: 'Hediye başarıyla açıldı!',
        giftOpenError: 'Hediye açılamadı',
        giftOpening: 'Hediye açılıyor...',
        openingGifts: 'Hediyeler açılıyor...',
        allGiftsOpened: 'Tüm hediyeler başarıyla açıldı!',
        scammerTest: 'Dolandırıcı Testi',
        securityStatus: 'Güvenlik Durumu',
        securitySafe: 'Güvenli',
        securitySuspicious: 'Şüpheli',
        securityUnsafe: 'Güvenli Değil',
        description: 'Açıklama',
        loadingComments: 'Yorumlar yükleniyor...',
        deletingComment: 'Yorum siliniyor...',
        commentDeleted: 'Yorum başarıyla silindi!',
        upgradeToObfxPlus: 'OBFX Plus\'a Yükselt',
        upgradeToObfxPro: 'OBFX Pro\'ya Yükselt',
        requiresLevel10OrPlus: 'Seviye 10+ veya OBFX Plus gerektirir',
        requiresObfxPro: 'OBFX Pro aboneliği gerektirir',
        planComparison: 'Plan Karşılaştırması',
        freePlan: 'Ücretsiz',
        plusPlan: 'OBFX Plus',
        proPlan: 'OBFX Pro',
        basic: 'Temel',
        standart: 'Standart',
        recommended: 'Önerilen',
        dailyTasksLevel10: 'Günlük Görevler (Seviye 10+)',
        limitedMoods: 'Sınırlı Ruh Halleri (7)',
        noGifts: 'Hediye Erişimi Yok',
        friendsManagement: 'Arkadaş Yönetimi',
        unlimitedDailyTasks: 'Sınırsız Günlük Görevler',
        allMoods: 'Tüm Ruh Halleri (37)',
        giftsAccess: 'Tam Hediye Erişimi',
        advancedFriends: 'Gelişmiş Arkadaş Özellikleri',
        prioritySupport: 'Öncelikli Destek',
        fastFeatures: 'Hızlı Özellikler',
        multiAccount: 'Çoklu Hesap Yönetimi',
        bulkOperations: 'Toplu İşlemler',
        detectiveService: 'Dedektiflik hizmeti',
        vipOnly: 'Sadece VIP',
        passwordChangeSuccess: 'Şifre başarıyla değiştirildi!',
        downloadAccountFile: 'Hesap dosyasını indirmek ister misiniz?',
        noThanks: 'Hayır, teşekkürler',
        whatsThis: 'Bu ne işe yarıyor?',
        yesRecommended: 'Evet (önerilir)',
        accountFileInfo: 'Hesap dosyası güncellenmiş kimlik bilgilerinizi içerir. Yedek olarak güvenli bir yerde saklamanızı öneriyoruz. Bu dosya, giriş bilgilerinizi unutursanız hesabınızı kurtarmanıza yardımcı olabilir.',
        accountFileInfoTitle: 'Hesap Dosyası Bilgisi',
        passwordChanging: 'Şifre değiştiriliyor...',
        passwordChangeError: 'Şifre değiştirilemedi',
        passwordMismatch: 'Şifreler eşleşmiyor',
        passwordTooShort: 'Şifre en az 6 karakter olmalıdır',
        fillAllFields: 'Lütfen tüm alanları doldurun',
        downloadStarted: 'Hesap dosyası indirimi başladı',
        currentPasswordWrong: 'Mevcut şifre yanlış',
        accountManagement: 'Hesap Yönetimi',
        accountInfo: 'Hesap Bilgileri',
        accountMethod: 'Hesap Yöntemi',
        websocketMethod: 'WebSocket Yöntemi',
        save: 'Kaydet',
        reset: 'Sıfırla',
        accounts: 'Hesaplar',
        normalTasks: 'Normal Günlük Görevler',
        fastTasks: 'Hızlı Günlük Görevler',
        accountSaved: 'Hesap başarıyla kaydedildi!',
        accountsReset: 'Tüm hesaplar sıfırlandı!',
        processingAccounts: 'Hesaplar işleniyor...',
        accountsProcessed: 'Tüm hesaplar işlendi!',

        // Account Info Section
        startDate: 'Başlangıç Tarihi',
        lastLoginDate: 'Son Giriş',
        location: 'Konum',
        houseName: 'Ev İsmi',
        lastUpdated: 'Son Güncelleme',
        numberOfArrangements: 'Düzenleme Sayısı',
        profileAnimLastModified: 'Profil Animasyonu Son Değişiklik Tarihi',
        numberOfChanges: 'Değişiklik Sayısı',
        homePhoto: 'Ev Fotoğrafı',
        loadingHomeImage: 'Ev görseli yükleniyor...',
        homeImageNotAvailable: 'Ev görseli mevcut değil',
        theHouse: ' Evi',
        searchingForUser: 'Kullanıcı aranıyor: ',
        accountInfoLoadedSuccess: 'Hesap bilgileri başarıyla yüklendi',
        errorLoadingAccountInfo: 'Hesap bilgileri yüklenirken hata oluştu',
        pleaseEnterUsername: 'Lütfen kullanıcı adını girin',
        userNotFound: ' bulunamadı',

        // General Notifications
        pleaseEnterWebsocketData: 'Lütfen WebSocket mesaj verilerini girin',
        invalidDataFormat: 'Geçersiz veri formatı. Lütfen girişinizi kontrol edin.',
        regionNotSupported: 'Bu bölge desteklenmiyor.',
        noAccountsToProcess: 'İşlenecek hesap yok',
        accountAlreadyExists: 'Hesap zaten mevcut',
        invalidWebsocketFormat: 'Geçersiz WebSocket veri formatı',
        noSecurityIssues: 'Bu kullanıcı için güvenlik sorunu bildirilmedi.',
        autoGreetingStarted: 'Otomatik selamlama başlatıldı: ',
        autoGreetingStopped: 'Otomatik selamlama durduruldu',
        sendingEveryTwoMinutes: ' - her 2 dakikada bir gönderiliyor',
        couldNotFindUser: 'Kullanıcı bulunamadı: ',
        autoGreetingAlreadyRunning: 'Otomatik selamlama zaten çalışıyor',
        pleaseLoginFirst: 'Lütfen önce giriş yapın',
        moodChangedSuccessfully: 'Ruh hali başarıyla değiştirildi!',
        failedToChangeMood: 'Ruh hali değiştirilemedi',
        errorChangingMood: 'Ruh hali değiştirilirken hata oluştu',
        genderChangedTo: 'Cinsiyet şu şekilde değiştirildi: ',
        failedToChangeGender: 'Cinsiyet değiştirilemedi',
        errorChangingGender: 'Cinsiyet değiştirilirken hata oluştu',
        noGiftsAvailable: 'Mevcut hediye yok',
        pleaseWait: 'Lütfen bekleyin...',
        friendRemovedSuccess: 'Arkadaş başarıyla kaldırıldı',
        errorRemovingFriend: 'Arkadaş kaldırılırken hata oluştu',
        friendRequestAccepted: 'Arkadaşlık isteği kabul edildi',
        errorAcceptingRequest: 'İstek kabul edilirken hata oluştu',
        friendRequestRejected: 'Arkadaşlık isteği reddedildi',
        errorRejectingRequest: 'İstek reddedilirken hata oluştu',
        userUnblockedSuccess: 'Kullanıcının engeli başarıyla kaldırıldı',
        errorUnblockingUser: 'Kullanıcının engeli kaldırılırken hata oluştu',
        noUsersToDelete: 'Bu kategoride silinecek kullanıcı yok',
        removingUsers: '{count} kullanıcı kaldırılıyor...',
        allUsersRemoved: 'Kategoriden tüm kullanıcılar kaldırıldı ({success}/{total})',
        errorRemovingAllUsers: 'Tüm kullanıcılar kaldırılırken hata oluştu',
        failedToOpenAnyGifts: 'Hiçbir hediye açılamadı',
        errorOpeningGifts: 'Hediyeler açılırken hata oluştu',
        startingEnhancedTasks: 'Gelişmiş günlük görevler başlatılıyor...',
        startingFastTasks: 'HIZLI günlük görevler başlatılıyor...',
        processingPetInteractions: 'Evcil hayvan etkileşimleri işleniyor...',
        completingDailyQuests: 'Günlük görevler tamamlanıyor...',
        processingVipGifts: 'VIP hediye görevleri işleniyor...',
        processingNormalGifts: 'Normal hediye görevleri işleniyor...',
        claimingVipRewards: 'VIP toplama ödülleri alınıyor...',
        claimingNormalRewards: 'Normal toplama ödülleri alınıyor...',
        processingAdditionalQuests: 'Ek görevler işleniyor...',
        allEnhancedTasksComplete: 'Tüm gelişmiş günlük görevler tamamlandı!',
        allFastTasksComplete: 'Tüm HIZLI günlük görevler tamamlandı!',
        enhancedTasksCompletedSuccess: 'Tüm gelişmiş günlük görevler başarıyla tamamlandı!',
        fastTasksCompletedSuccess: 'Tüm HIZLI günlük görevler başarıyla tamamlandı!',
        errorDuringExecution: 'Yürütme sırasında hata oluştu',
        errorDuringDailyTasks: 'Günlük görevler yürütülürken hata oluştu',
        errorDuringFastTasks: 'HIZLI günlük görevler yürütülürken hata oluştu',
        fastProcessingAllTasks: 'HIZLI: Tüm görevler paralel olarak işleniyor...',
        fastExecutingSimultaneously: 'HIZLI: Tüm görevler aynı anda yürütülüyor...',
        openedGiftsPartial: '{success}/{total} hediye başarıyla açıldı',
        loggedOutSuccessfully: 'Başarıyla çıkış yapıldı. Hesap bilgileri ve yakınlaştırma ayarı korundu.',
        languageChangedTo: 'Dil şu şekilde değiştirildi: ',
        accountDataNotAvailable: 'İndirilebilir hesap verisi mevcut değil',
        errorLoadingFriendsData: 'Arkadaş verileri yüklenirken hata oluştu',
        loadingConversations: 'Konuşmalar yükleniyor...',
        noConversations: 'Konuşma bulunamadı',
        failedToLoadConversations: 'Konuşmalar yüklenemedi',
        errorLoadingConversations: 'Konuşmalar yüklenirken hata oluştu',
        loadingMessages: 'Mesajlar yükleniyor...',
        noMessages: 'Bu konuşmada mesaj yok',
        failedToLoadMessages: 'Mesajlar yüklenemedi',
        errorLoadingMessages: 'Mesajlar yüklenirken hata oluştu',
        unknownUser: 'Bilinmeyen Kullanıcı',
        failedToLoad: 'Yüklenemedi',
        errorLoading: 'Yükleme Hatası',
        backToInbox: 'Gelen Kutusuna Dön',
        inbox: 'Gelen Kutusu',
        noMessage: 'Mesaj yok',
        fromUser: 'Kimden: '
    },
    az: {
        title: 'MSP2 - OBFX®',
        language: 'Dil',
        zoom: 'Yaxınlaşdırma',
        plan: 'Plan',
        obfx: 'OBFX',
        obfxPro: 'OBFX Pro',
        autograph: 'İmza',
        changePassword: 'Şifrəni Dəyiş',
        exit: 'Çıxış',
        welcomeTitle: 'MSP2 Alətinə Xoş Gəldiniz',
        welcomeSubtitle: 'Giriş üsulunuzu seçin',
        websocketLogin: 'WebSocket Girişi',
        accountLogin: 'Hesab Girişi',
        websocketPlaceholder: 'WebSocket mesajını bura yapışdırın...',
        usernamePlaceholder: 'İstifadəçi Adı',
        passwordPlaceholder: 'Şifrə',
        login: 'Giriş',
        loading: 'Yüklənir...',
        querySent: 'Sorğu göndərildi...',
        approvedLogin: 'Təsdiqləndi, giriş edilir...',
        banned: 'Qadağan edildiniz!',
        bannedMessage: 'OBFX bu hesaba giriş etməyi dəstəkləmir.',
        backToLogin: 'Ana Ekrana Qayıt',
        menu: 'Menyu',
        changeMood: 'Ruh-Halı Dəyiş',
        gender: 'Cins',
        gifts: 'Hədiyyələr',
        dailyTask: 'Gündəlik Tapşırıq',
        startEnhanced: 'Başlat',
        fastStart: 'Sürətli Başlat',
        applyMood: 'Əhval-Ruhiyyəni Tətbiq Et',
        currentPassword: 'Mövcud Şifrə',
        newPassword: 'Yeni Şifrə',
        confirmPassword: 'Yeni Şifrəni Təstiq Et',
        cancel: 'Ləğv Et',
        enterUsername: 'İstifadəçi adını daxil edin',
        findStart: 'Tap və Başlat',
        stop: 'Dayandır',
        test: 'Test',
        totalFame: 'Ümumi Şöhrət:',
        close: 'Bağla',
        languageSelection: 'Dil Seçimi',
        currentLanguage: 'Mövcud Dil:',
        zoomLevel: 'Yaxınlaşdırma Səviyyəsi',
        selectRegion: 'Region Seç',
        selectRegionDesc: 'Giriş etməzdən əvvəl regionunuzu seçin:',
        unitedStates: 'Amerika Birləşmiş Ştatları',
        europe: 'Avropa',
        warning: 'Xəbərdarlıq!',
        fastWarning1: 'Sürətli tamamlama hesabın askıya alınmasına və ya qadağan edilməsinə səbəb ola bilər.',
        startFastMode: 'Sürətli Rejimi Başlat',
        comments: 'Şərhlər',
        noComments: 'Hələ şərh yoxdur',
        status: 'Vəziyyət',
        openAllGifts: 'Bütün Hədiyyələri Aç',
        sessionExpired: 'Sessiya müddəti bitdi. Təkrar giriş edin.',
        tokenExpiring: 'Sessiya 15 dəqiqədə sona çatacaq.',
        loginSuccess: 'Giriş uğurlu oldu!',
        loginError: 'Giriş uğursuz. Məlumatlarınızı yoxlayın.',
        invalidCredentials: 'Yanlış istifadəçi adı və ya şifrə.',
        connectionError: 'Bağlantı xətası. Təkrar cəhd edin.',
        friendsSettings: 'Dost Parametrləri',
        friends: 'Dostlar',
        requestSenders: 'İstək Göndərənlər',
        blocked: 'Əngəllənmiş',
        deleteAll: 'Hamısını Sil',
        loadingFriends: 'Dostlar yüklənir...',
        loadingRequests: 'İstəklər yüklənir...',
        loadingBlocked: 'Əngəllənmişlər yüklənir...',
        noFriends: 'Dost tapılmadı',
        noRequests: 'Dostluq istəyi yoxdur',
        noBlocked: 'Əngəllənmiş istifadəçi yoxdur',
        level: 'Səviyyə',
        lastLogin: 'Son Giriş',
        remove: 'Sil',
        accept: 'Qəbul Et',
        reject: 'Rədd Et',
        unblock: 'Əngəli Götür',
        dangerousAction: 'Təhlükəli Əməliyyat!',
        deleteAllWarning: 'Bu əməliyyat seçilən kateqoriyadakı BÜTÜN istifadəçiləri siləcək. Bu riskli bir işdir və geri alına bilməz!',
        waitCountdown: 'Geri sayımın bitməsini gözləyin...',
        yes: 'Bəli',
        no: 'Xeyr',
        giftOpenSuccess: 'Hədiyyə uğurla açıldı!',
        giftOpenError: 'Hədiyyə açılmadı',
        giftOpening: 'Hədiyyə açılır...',
        openingGifts: 'Hədiyyələr açılır...',
        allGiftsOpened: 'Bütün hədiyyələr uğurla açıldı!',
        scammerTest: 'Fırıldaqçı Testi',
        securityStatus: 'Təhlükəsizlik Vəziyyəti',
        securitySafe: 'Təhlükəsiz',
        securitySuspicious: 'Şübhəli',
        securityUnsafe: 'Təhlükəsiz Deyil',
        description: 'Təsvir',
        loadingComments: 'Şərhlər yüklənir...',
        deletingComment: 'Şərh silinir...',
        commentDeleted: 'Şərh uğurla silindi!',
        upgradeToObfxPlus: 'OBFX Plus-a Yüksəlt',
        upgradeToObfxPro: 'OBFX Pro-ya Yüksəlt',
        requiresLevel10OrPlus: 'Səviyyə 10+ və ya OBFX Plus tələb edir',
        requiresObfxPro: 'OBFX Pro abunəliyi tələb edir',
        planComparison: 'Plan Müqayisəsi',
        freePlan: 'Pulsuz',
        plusPlan: 'OBFX Plus',
        proPlan: 'OBFX Pro',
        basic: 'Əsas',
        standart: 'Standart',
        recommended: 'Tövsiyə olunur',
        dailyTasksLevel10: 'Gündəlik Tapşırıqlar (Səviyyə 10+)',
        limitedMoods: 'Məhdud Əhval-Ruhiyyələr (7)',
        noGifts: 'Hədiyyə Girişi Yoxdur',
        friendsManagement: 'Dost İdarəetməsi',
        unlimitedDailyTasks: 'Məhdudiyyətsiz Gündəlik Tapşırıqlar',
        allMoods: 'Bütün Əhval-Ruhiyyələr (37)',
        giftsAccess: 'Tam Hədiyyə Girişi',
        advancedFriends: 'Təkmil Dost Xüsusiyyətləri',
        prioritySupport: 'Prioritet Dəstəyi',
        fastFeatures: 'Sürətli Xüsusiyyətlər',
        multiAccount: 'Çoxlu Hesab İdarəetməsi',
        bulkOperations: 'Toplu Əməliyyatlar',
        detectiveService: 'Dedektif xidməti',
        vipOnly: 'Yalnız VIP',
        passwordChangeSuccess: 'Şifrə uğurla dəyişdirildi!',
        downloadAccountFile: 'Hesab faylını yükləmək istəyirsiniz?',
        noThanks: 'Xeyr, təşəkkür edirəm',
        whatsThis: 'Bu nə üçündür?',
        yesRecommended: 'Bəli (tövsiyə olunur)',
        accountFileInfo: 'Hesab faylı yenilənmiş giriş məlumatlarınızı ehtiva edir. Ehtiyat olaraq təhlükəsiz yerdə saxlamağı tövsiyə edirik. Bu fayl giriş məlumatlarınızı unutsanız hesabınızı bərpa etməyə kömək edə bilər.',
        accountFileInfoTitle: 'Hesab Faylı Məlumatı',
        passwordChanging: 'Şifrə dəyişdirilir...',
        passwordChangeError: 'Şifrə dəyişdirilə bilmədi',
        passwordMismatch: 'Şifrələr uyğun gəlmir',
        passwordTooShort: 'Şifrə ən az 6 simvol olmalıdır',
        fillAllFields: 'Bütün sahələri doldurun',
        downloadStarted: 'Hesab faylı yüklənməsi başladı',
        currentPasswordWrong: 'Mövcud şifrə səhvdir',
        accountManagement: 'Hesab İdarəetməsi',
        accountInfo: 'Hesab Məlumatları',
        accountMethod: 'Hesab Üsulu',
        websocketMethod: 'WebSocket Üsulu',
        save: 'Saxla',
        reset: 'Sıfırla',
        accounts: 'Hesablar',
        normalTasks: 'Normal Gündəlik Tapşırıqlar',
        fastTasks: 'Sürətli Gündəlik Tapşırıqlar',
        accountSaved: 'Hesab uğurla saxlanıldı!',
        accountsReset: 'Bütün hesablar sıfırlandı!',
        processingAccounts: 'Hesablar emal olunur...',
        accountsProcessed: 'Bütün hesablar emal olundu!',

        // Account Info Section
        startDate: 'Başlama Tarixi',
        lastLoginDate: 'Son Giriş',
        location: 'Məkan',
        houseName: 'Ev Adı',
        lastUpdated: 'Son Yenilənmə',
        numberOfArrangements: 'Düzənləmələrin Sayı',
        profileAnimLastModified: 'Profil Animasiyasının Son Dəyişiklik Tarixi',
        numberOfChanges: 'Dəyişikliklərin Sayı',
        homePhoto: 'Ev Şəkli',
        loadingHomeImage: 'Ev şəkli yüklənir...',
        homeImageNotAvailable: 'Ev şəkli mövcud deyil',
        theHouse: ' Evi',
        searchingForUser: 'İstifadəçi axtarılır: ',
        accountInfoLoadedSuccess: 'Hesab məlumatları uğurla yükləndi',
        errorLoadingAccountInfo: 'Hesab məlumatları yüklənərkən xəta baş verdi',
        pleaseEnterUsername: 'Xahiş edirik istifadəçi adını daxil edin',
        userNotFound: ' tapılmadı',

        // General Notifications
        pleaseEnterWebsocketData: 'Xahiş edirik WebSocket mesaj məlumatlarını daxil edin',
        invalidDataFormat: 'Yanlış məlumat formatı. Xahiş edirik girişinizi yoxlayın.',
        regionNotSupported: 'Bu region dəstəklənmir.',
        noAccountsToProcess: 'Emal ediləcək hesab yoxdur',
        accountAlreadyExists: 'Hesab artıq mövcuddur',
        invalidWebsocketFormat: 'Yanlış WebSocket məlumat formatı',
        noSecurityIssues: 'Bu istifadəçi üçün təhlükəsizlik problemi bildirilməyib.',
        autoGreetingStarted: 'Avtomatik salamlama başladı: ',
        autoGreetingStopped: 'Avtomatik salamlama dayandırıldı',
        sendingEveryTwoMinutes: ' - hər 2 dəqiqədən bir göndərilir',
        couldNotFindUser: 'İstifadəçi tapılmadı: ',
        autoGreetingAlreadyRunning: 'Avtomatik salamlama artıq işləyir',
        pleaseLoginFirst: 'Xahiş edirik əvvəlcə giriş edin',
        moodChangedSuccessfully: 'Əhval-ruhiyyə uğurla dəyişdirildi!',
        failedToChangeMood: 'Əhval-ruhiyyə dəyişdirilə bilmədi',
        errorChangingMood: 'Əhval-ruhiyyə dəyişdirilərkən xəta baş verdi',
        genderChangedTo: 'Cins belə dəyişdirildi: ',
        failedToChangeGender: 'Cins dəyişdirilə bilmədi',
        errorChangingGender: 'Cins dəyişdirilərkən xəta baş verdi',
        noGiftsAvailable: 'Mövcud hədiyyə yoxdur',
        pleaseWait: 'Xahiş edirik gözləyin...',
        friendRemovedSuccess: 'Dost uğurla silindi',
        errorRemovingFriend: 'Dost silinərkən xəta baş verdi',
        friendRequestAccepted: 'Dostluq istəyi qəbul edildi',
        errorAcceptingRequest: 'İstək qəbul edilərkən xəta baş verdi',
        friendRequestRejected: 'Dostluq istəyi rədd edildi',
        errorRejectingRequest: 'İstək rədd edilərkən xəta baş verdi',
        userUnblockedSuccess: 'İstifadəçinin əngəli uğurla götürüldü',
        errorUnblockingUser: 'İstifadəçinin əngəli götürülərkən xəta baş verdi',
        noUsersToDelete: 'Bu kateqoriyada silinəcək istifadəçi yoxdur',
        removingUsers: '{count} istifadəçi silinir...',
        allUsersRemoved: 'Kateqoriyadan bütün istifadəçilər silindi ({success}/{total})',
        errorRemovingAllUsers: 'Bütün istifadəçilər silinərkən xəta baş verdi',
        failedToOpenAnyGifts: 'Heç bir hədiyyə açıla bilmədi',
        errorOpeningGifts: 'Hədiyyələr açılarkən xəta baş verdi',
        startingEnhancedTasks: 'Təkmilləşdirilmiş gündəlik tapşırıqlar başladılır...',
        startingFastTasks: 'SÜRƏTLİ gündəlik tapşırıqlar başladılır...',
        processingPetInteractions: 'Ev heyvanları qarşılıqlı əlaqələri emal olunur...',
        completingDailyQuests: 'Gündəlik tapşırıqlar tamamlanır...',
        processingVipGifts: 'VIP hədiyyə tapşırıqları emal olunur...',
        processingNormalGifts: 'Normal hədiyyə tapşırıqları emal olunur...',
        claimingVipRewards: 'VIP toplama mükafatları alınır...',
        claimingNormalRewards: 'Normal toplama mükafatları alınır...',
        processingAdditionalQuests: 'Əlavə tapşırıqlar emal olunur...',
        allEnhancedTasksComplete: 'Bütün təkmilləşdirilmiş gündəlik tapşırıqlar tamamlandı!',
        allFastTasksComplete: 'Bütün SÜRƏTLİ gündəlik tapşırıqlar tamamlandı!',
        enhancedTasksCompletedSuccess: 'Bütün təkmilləşdirilmiş gündəlik tapşırıqlar uğurla tamamlandı!',
        fastTasksCompletedSuccess: 'Bütün SÜRƏTLİ gündəlik tapşırıqlar uğurla tamamlandı!',
        errorDuringExecution: 'İcra zamanı xəta baş verdi',
        errorDuringDailyTasks: 'Gündəlik tapşırıqlar icra edilərkən xəta baş verdi',
        errorDuringFastTasks: 'SÜRƏTLİ gündəlik tapşırıqlar icra edilərkən xəta baş verdi',
        fastProcessingAllTasks: 'SÜRƏTLİ: Bütün tapşırıqlar paralel olaraq emal olunur...',
        fastExecutingSimultaneously: 'SÜRƏTLİ: Bütün tapşırıqlar eyni vaxtda icra olunur...',
        openedGiftsPartial: '{success}/{total} hədiyyə uğurla açıldı',
        loggedOutSuccessfully: 'Uğurla çıxış edildi. Hesab məlumatları və yaxınlaşdırma ayarı qorundu.',
        languageChangedTo: 'Dil belə dəyişdirildi: ',
        accountDataNotAvailable: 'Yüklənə bilən hesab məlumatı yoxdur',
        errorLoadingFriendsData: 'Dost məlumatları yüklənərkən xəta baş verdi',
        loadingConversations: 'Söhbətlər yüklənir...',
        noConversations: 'Söhbət tapılmadı',
        failedToLoadConversations: 'Söhbətlər yüklənə bilmədi',
        errorLoadingConversations: 'Söhbətlər yüklənərkən xəta baş verdi',
        loadingMessages: 'Mesajlar yüklənir...',
        noMessages: 'Bu söhbətdə mesaj yoxdur',
        failedToLoadMessages: 'Mesajlar yüklənə bilmədi',
        errorLoadingMessages: 'Mesajlar yüklənərkən xəta baş verdi',
        unknownUser: 'Naməlum İstifadəçi',
        failedToLoad: 'Yüklənə Bilmədi',
        errorLoading: 'Yüklənmə Xətası',
        backToInbox: 'Gələn Qutusuna Qayıt',
        inbox: 'Gələn Qutusu',
        noMessage: 'Mesaj yoxdur',
        fromUser: 'Kimdən: '
    }
};

// Console log to verify loading
console.log('Language.js loaded successfully!', window.TRANSLATIONS ? 'Translations available' : 'Translations missing');

// Helper function to get translated text with fallback
window.getTranslation = function(key, fallback = '') {
    const currentLang = window.currentLanguage || 'en';
    const translations = window.TRANSLATIONS[currentLang] || window.TRANSLATIONS.en;
    return translations[key] || fallback || key;
};

// Helper function for parameterized translations
window.getTranslationWithParams = function(key, params = {}, fallback = '') {
    let text = window.getTranslation(key, fallback);
    
    // Replace parameters in the text
    Object.keys(params).forEach(param => {
        const regex = new RegExp(`{${param}}`, 'g');
        text = text.replace(regex, params[param]);
    });
    
    return text;
};

// Updated showNotification function that uses translations
window.showNotificationTranslated = function(translationKey, type = 'info', params = {}, fallback = '') {
    const message = params && Object.keys(params).length > 0 
        ? window.getTranslationWithParams(translationKey, params, fallback)
        : window.getTranslation(translationKey, fallback);
    
    const container = document.getElementById('notificationContainer');
    if (!container) return;
    
    const notification = document.createElement('div');
    notification.className = `notification ${type}`;
    notification.textContent = message;

    container.appendChild(notification);

    setTimeout(() => {
        notification.classList.add('show');
    }, 100);

    setTimeout(() => {
        notification.classList.remove('show');
        setTimeout(() => {
            if (notification.parentNode) {
                notification.parentNode.removeChild(notification);
            }
        }, 400);
    }, 3000);
};
